"""add tags to tracks

Revision ID: 0951f1ba14dd
Revises: 7382c88d5b2a
Create Date: 2026-06-19 19:04:18.940516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0951f1ba14dd'
down_revision: Union[str, None] = '7382c88d5b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'tags')
    # ### end Alembic commands ###
