"""add album_art_url to tracks

Revision ID: 19fd13563cb9
Revises: d08423fdd3cb
Create Date: 2026-06-28 22:06:41.488125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19fd13563cb9'
down_revision: Union[str, None] = 'd08423fdd3cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('album_art_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'album_art_url')
    # ### end Alembic commands ###
