"""initial

Revision ID: 7382c88d5b2a
Revises: 
Create Date: 2026-06-19 00:08:03.317171

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7382c88d5b2a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('track_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('playlist_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('type', sa.Enum('LIKE', 'DISLIKE', 'SKIP', 'SAVE_PLAYLIST', 'EDIT_PLAYLIST', 'DISMISS', name='feedback_type_enum'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('context_playlist_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intent_sessions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source', sa.Enum('QUESTIONNAIRE', 'NLP_PROMPT', name='intent_source_enum'), nullable=False),
    sa.Column('raw_input', sa.JSON(), nullable=False),
    sa.Column('extracted_intent', sa.JSON(), nullable=True),
    sa.Column('intent_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlists',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('intent_session_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('theme_label', sa.String(), nullable=True),
    sa.Column('track_ids', sa.ARRAY(sa.UUID(as_uuid=False)), nullable=False),
    sa.Column('generation_mode', sa.Enum('PLAYLIST_GEN', 'RECOMMENDATION', name='generation_mode_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('feedback', sa.Enum('SAVED', 'DISMISSED', 'EDITED', name='playlist_feedback_enum'), nullable=True),
    sa.Column('edited_track_ids', sa.ARRAY(sa.UUID(as_uuid=False)), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('spotify_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=False),
    sa.Column('album', sa.String(), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('valence', sa.Float(), nullable=True),
    sa.Column('tempo', sa.Float(), nullable=True),
    sa.Column('danceability', sa.Float(), nullable=True),
    sa.Column('acousticness', sa.Float(), nullable=True),
    sa.Column('instrumentalness', sa.Float(), nullable=True),
    sa.Column('liveness', sa.Float(), nullable=True),
    sa.Column('speechiness', sa.Float(), nullable=True),
    sa.Column('loudness', sa.Float(), nullable=True),
    sa.Column('mode', sa.Integer(), nullable=True),
    sa.Column('key', sa.Integer(), nullable=True),
    sa.Column('genres', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spotify_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('spotify_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('preference_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('preference_source', sa.Enum('QUESTIONNAIRE', 'HISTORY', 'HYBRID', name='preference_source_enum'), nullable=True),
    sa.Column('preference_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('liked_track_ids', sa.ARRAY(sa.UUID(as_uuid=False)), nullable=True),
    sa.Column('disliked_track_ids', sa.ARRAY(sa.UUID(as_uuid=False)), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('tracks')
    op.drop_table('playlists')
    op.drop_table('intent_sessions')
    op.drop_table('feedback_events')
    # ### end Alembic commands ###
