"""initial_schema

Revision ID: d08423fdd3cb
Revises: 
Create Date: 2026-06-23 13:49:31.479075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'd08423fdd3cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('spotify_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=False),
    sa.Column('album', sa.String(), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('genres', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spotify_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('spotify_user_id', sa.String(), nullable=True),
    sa.Column('spotify_access_token', sa.String(), nullable=True),
    sa.Column('spotify_refresh_token', sa.String(), nullable=True),
    sa.Column('spotify_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('spotify_authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clustering_runs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('n_clusters', sa.Integer(), nullable=False),
    sa.Column('algorithm', sa.String(), nullable=False),
    sa.Column('outlier_threshold', sa.Float(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_tracks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('track_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.Enum('SEARCH', 'PLAYLIST_IMPORT', 'LIKED_SONGS', name='collection_source_enum'), nullable=False),
    sa.Column('source_spotify_playlist_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'track_id', name='uq_collection_user_track')
    )
    op.create_table('intent_sessions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('raw_prompt', sa.String(), nullable=False),
    sa.Column('intent_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlists',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('intent_session_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('clustering_run_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('generation_mode', sa.Enum('TARGETED', 'CLUSTERED', name='generation_mode_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clustering_run_id'], ['clustering_runs.id'], ),
    sa.ForeignKeyConstraint(['intent_session_id'], ['intent_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('track_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('playlist_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('type', sa.Enum('LIKE', 'DISLIKE', 'SKIP', 'SAVE_PLAYLIST', 'DISMISS', name='feedback_type_enum'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlist_tracks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('playlist_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('track_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playlist_id', 'track_id', name='uq_playlist_track')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_tracks')
    op.drop_table('feedback_events')
    op.drop_table('playlists')
    op.drop_table('intent_sessions')
    op.drop_table('collection_tracks')
    op.drop_table('clustering_runs')
    op.drop_table('users')
    op.drop_table('tracks')
    # ### end Alembic commands ###
